export default Object.freeze({
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_NAME: "INVALID_NAME",
  INVALID_OTP: "INVALID_OTP",
  USER_NOT_FOUND: "USER_NOT_FOUND",
});
