export default Object.freeze({
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_DATA: "INVALID_DATA",
  INVALID_NAME: "INVALID_NAME",
  INVALID_OTP: "INVALID_OTP",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
});
